### ISSUE TITLE
Tracker: Web app protocol parity with TUI

### ISSUE THREAD

**Issue by ethanuppal** [ethanuppal/nerdtalk#37]
- [ ] Bind to rust to communicate with server through the `client-connect` crate
- [ ] Support `ServerMessage::NewEntry`
- [ ] Support the `ServerMessage` (to be named) for responding to history requests
